spring:
  application:
    name: consul-client-consumer
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        instance-group: ccc
      host: localhost
      port: 8500

services:
  provider: consul-client-provider

server:
  port: 3302

management:
  server:
    port: 3300

resilience4j.circuitbreaker:
  instances:
    consul-client-provider:
      failureRateThreshold: 50
      minimumNumberOfCalls: 10
      slidingWindowType: TIME_BASED
      slidingWindowSize: 10
      waitDurationInOpenState: 50s
      permittedNumberOfCallsInHalfOpenState: 3